swagger: "2.0"
info:
  title: "SSRF Testing"
  version: "1.0.0"
paths:
  /:
    get:
      responses:
        200:
          description: "Test SSRF with CanaryToken"
          schema:
            $ref: "996q5r8xqfl1xyqeyj9zrrg82.canarytokens.com"
