swagger: "2.0"
info:
  title: "SSRF Query Param Test"
  version: "1.0"
host: "api.tektiklaode.visa.com.tr"
schemes:
  - https
paths:
  /admin-check:
    get:
      parameters:
        - name: "url"
          in: "query"
          required: true
          type: "string"
          example: "https://webhook.site/a44f8421-8b84-4309-bd87-18a8fb8ddc06"
      responses:
        200:
          description: "SSRF test with URL param"
