swagger: "2.0"
info:
  title: "SSRF Testing"
  version: "1.0.0"
paths:
  /test:
    get:
      parameters:
        - in: query
          name: url
          type: string
          required: true
          description: "URL to fetch (SSRF test)"
          default: "http://127.0.0.1:8081/"
      responses:
        200:
          description: "Successful SSRF test"
          schema:
            type: string
